name: Build and Release

on:
  push:
    tags:
      - v0.2-beta  # Match tags like v0.2-beta, v1.0, etc.

jobs:
  build-and-release:
    name: Build and Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build binary with PyInstaller
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile --icon=assets/icons/myicon.ico melaninclick_windows.py
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
            pyinstaller --onefile --icon=assets/icons/myicon.icns melaninclick_macos.py
        else
            pyinstaller --onefile --icon=assets/icons/myicon.png melaninclick_linux.py  
        fi
      # After this step, you'll have your output ready.

    - name: Create Release
      id: create_release
      uses: gh-actions/create-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: MelaninClick ${{ github.ref }}
        draft: false
        prerelease: true  # Set this to 'false' if it's a stable release.

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/your_script${{ runner.os == 'Windows' && '.exe' || (runner.os == 'macOS' && '.app') || (runner.os == 'Linux' && '.AppImage') }}
        asset_name: melaninclick-${{ github.ref }}-${{ runner.os == 'Windows' && '.exe' || (runner.os == 'macOS' && '.app') || (runner.os == 'Linux' && '.AppImage') }}
        # The resulting name will be something like `melaninclick-v0.2-beta-Linux.AppImage`
        asset_content_type: application/octet-stream
